services:
  postgres:
    image: postgres:16
    container_name: all-notes
    restart: unless-stopped

    environment:
      POSTGRES_USER: all-notes
      POSTGRES_PASSWORD: all-notes
      POSTGRES_DB: all-notes

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
